BIBLIOTECAS

In [10]:
from math import sqrt,factorial
import random


CONDICIONAIS

REPETIÇÃO

LISTAS, TUPLAS E DICIONÁRIOS

FUNÇÕES

LAMBDA E MAP

In [12]:
# lambda
area_quadrado = lambda x: x**2
area_quadrado(3)

9

In [15]:
# map - associar uma função a variavel
L = [4,5,6,7,11,9,10]
areas = list(map(lambda x: x**2,L))
print(areas)

[16, 25, 36, 49, 121, 81, 100]


LIST COMPREHENSIONS

In [17]:
# metodo longo

lista = []
for valor in range(5):
    lista.append(valor+10)
print(lista)

[10, 11, 12, 13, 14]


In [18]:
# Metodo reduzido

lista = [valor+10 for valor in range(5)]
print(lista)

[10, 11, 12, 13, 14]


In [19]:
# Metodo longo 2

multiplos = []
for numero in range(1,30):
    if numero % 4 == 0:
        multiplos.append(numero)
print(multiplos)

[4, 8, 12, 16, 20, 24, 28]


In [21]:
# Metodo reduzido 2
multiplos = [numero for numero in range(1,30) if numero % 4 == 0]
print(multiplos)

[4, 8, 12, 16, 20, 24, 28]


In [22]:
conceito = ["azul" if nota>=6 else "vermelha" for nota in range(1,11)]
print(conceito)

['vermelha', 'vermelha', 'vermelha', 'vermelha', 'vermelha', 'azul', 'azul', 'azul', 'azul', 'azul']


VETORES E MATRIZES

In [23]:
vetor = [2,4,5,6]
matriz = [[1,2,3],[4,5,6],[7,8,9]]

import numpy as np

vetor2 = np.array([1,-3,4,0.5])
matriz2 = np.ones((2,3))

In [27]:
print(vetor2)

[ 1.  -3.   4.   0.5]


In [28]:
print(matriz2)

[[1. 1. 1.]
 [1. 1. 1.]]


In [29]:
matriz3 = np.diag((2,4,6,8,10))
print(matriz3)

[[ 2  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  6  0  0]
 [ 0  0  0  8  0]
 [ 0  0  0  0 10]]
